### ISSUE TITLE
calculate ai output file empty

### ISSUE THREAD

**Issue by mgarl-10** [GDKO/AvP#10]
Hello,

Thank you for such a nice program. I am preparing the input files and I tried to get the ai.out file from my blast searches and the groups.yaml, however the output file is empty. I get something like this:

query name      donor   ingroup AI      HGTindex        query hits number       AHS     outg_pct
gene_1   ::::    ::::    0.0     0       500     0       0
gene_2   ::::    ::::    0.0     0       115     0       0
gene_3   ::::    ::::    0.0     0       608     0       0
gene_4   ::::    ::::    0.0     0       511     0       0
gene_5   ::::    ::::    0.0     0       43      0       0

Do you know what might be wrong?

Thanks

**Comment by GDKO** [comment]
Hi @mgarl-10,

Can you attach the 2000 first lines of your blast file and the groups.yaml file here or send them to my email?

Cheers,
Georgios

**Comment by mgarl-10** [comment]
Here they are:

[groups.yaml.txt](https://github.com/GDKO/AvP/files/11848152/groups.yaml.txt)
[blast_similarity.txt](https://github.com/GDKO/AvP/files/11848153/blast_similarity.txt)

**Comment by GDKO** [comment]
You have send me the output of calculate_ai.py instead of the output of blast :).

**Comment by mgarl-10** [comment]
My bad X)
Here it is:

[blast_similarity.txt](https://github.com/GDKO/AvP/files/11848426/blast_similarity.txt)

**Comment by GDKO** [comment]
I see no issues from my end. I run the command
```~/software/AvP/aux_scripts/calculate_ai.py -i blast_similarity.txt -x groups.yaml.txt``` 
and I got the attached results
[blast_similarity_ai.txt](https://github.com/GDKO/AvP/files/11848644/blast_similarity_ai.txt)

Do you get any errors when you run the script?

**Comment by mgarl-10** [comment]
Maybe there is something wrong with my installation but I did not get any errors.

**Comment by GDKO** [comment]
Can you test on the same test files you attached? Just in case there is an error with the full blast.

**Comment by mgarl-10** [comment]
Hello @GDKO 
I get a similar output as with the complete file.

**Comment by GDKO** [comment]
Before diving deeper, is it possible to test on a different environment or machine?

**Comment by mgarl-10** [comment]
It is working now!
The taxadb had not been downloaded properly for some reason. 
Thank you @GDKO  :)

**Comment by huiifeng** [comment]
Hi, I am having a similar problem here.
I want to use avp to detect a list of protein of bacteria (Saccharimonadia) and where it may came from. And I am using uniport90 as a database, I get an empty file of ai output. 

`python ~/AvP/aux_scripts/calculate_ai.py -i 3.uniref90.out -x groups.yaml
[!] Skipped 34000 hits
head 3.uniref90.out_ai.out
query name	donor	ingroup	AI	HGTindex	query hits number   AHS	outg_pct'

And in attachment you can find the config (group) file and top 1000 lines of the blast output file.

Best regards
Hu

[groups.yaml.txt](https://github.com/user-attachments/files/20946776/groups.yaml.txt)
[uniref90.out.txt](https://github.com/user-attachments/files/20946775/uniref90.out.txt)

**Comment by GDKO** [comment]
Hi @huiifeng,

Have you formatted the uniref90 database according to the [wiki](https://github.com/GDKO/AvP/wiki/Setting-up#uniref90)? 

Cheers,
Georgios

**Comment by huiifeng** [comment]
Hi Georgios

Yes, my uniref90 database look like  ">Uniref90|UniRef90_UPI002E2621C6"

Best,
Hu

**Comment by GDKO** [comment]
Can you post your diamond commands?

**Comment by huiifeng** [comment]
Yes:
diamond blastp -q *.faa -d uniref90.fasta.dmnd --evalue 1e-5 --max-target-seqs 500 --tmpdir $TMPDIR --out uniref90.out \
 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids

**Comment by GDKO** [comment]
It feels like the issue is your diamond makedb command. Can you post that as well and the diamond version?

**Comment by huiifeng** [comment]
diamond makedb --in uniref90.fasta.fixed.gz --taxonmap un.taxids --db uniref90.fasta.dmnd --taxonnodes nodes.dmp --taxonnames names.dmp --tmpdir $TMPDIR

diamond v2.1.12.166

**Comment by GDKO** [comment]
Ok, all looks fine. Let me check one last thing and I will get back to you.

**Comment by huiifeng** [comment]
Thanks!

**Comment by GDKO** [comment]
Hi @huiifeng,

Based on your ```blast_similarity.txt``` the database does not contain any taxids associated to the sequences within the database. This points to an error during the diamond database creation process. I have tested from scratch the creation of the uniref db and it works as expected on my end.

So one of these commands must create the problem

1. ```sed 's/>/>Uniref90|/' <(zcat uniref90.fasta.gz) | gzip > uniref90.fasta.fixed.gz```
     -  Based on your feedback, your database contains headers like ```Uniref90|UniRef90_UPI002E2621C6``` so this is not the problem
2. ```acc2taxid.py -i uniref90.fasta.fixed.gz -m uniref > un.taxids```
     -  Can you check the first lines of the ```un.taxids``` file if they look like this 
```
accession.version       taxid
UniRef90_UPI002E2621C6  121492
 ```
3. ```diamond makedb --in uniref90.fasta.fixed.gz --taxonmap un.taxids --db uniref90.fasta.dmnd --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp```
     -  Do you have the last 8 lines from your ```diamond makedb``` command output? For example mine looks like this
```
Database sequences                   208005650
Database letters                     71627808805
Accessions in database               208005650
Entries in accession to taxid file   208005650
Database accessions mapped to taxid  208005650
Database sequences mapped to taxid   208005650
Database hash                        5614cbd59f92d291ce5d66936b7085d3
Total time                           6292s
```

Cheers,
Georgios

**Comment by huiifeng** [comment]
Hi Georgios,

I agree that the problem is the makedatabase.

My un.taxids file looks like yours 

> accession.version	taxid
UniRef90_UPI002E2621C6	121492

However, the last 8 line of my diamond makedb shows:

> Database sequences                   205738716
Database letters                     70751878138
Accessions in database               205738801
Entries in accession to taxid file   205738716
Database accessions mapped to taxid  0
Database sequences mapped to taxid   0
Database hash                        09c736abc103ef3667e1fa3207d09bd0
Total time                           6864s

There is nothing mapped to the taxid.

Here is the command I used:

> diamond makedb --in uniref90.fasta.fixed.gz --taxonmap un.taxids --db uniref90.fasta.dmnd --taxonnodes nodes.dmp --taxonnames names.dmp --tmpdir $TMPDIR

Do you have any clue what cause the problem?

Best,
Hu

**Comment by huiifeng** [comment]
`diamond makedb --in uniref90.fasta.fixed.gz --taxonmap un.taxids --db uniref90.fasta.dmnd --taxonnodes nodes.dmp --taxonnames names.dmp --tmpdir $TMPDIR`

**Comment by GDKO** [comment]
Can you select the first 100 sequences from uniref and then do the whole 3 command creation step? And post the last lines from makedb

**Comment by huiifeng** [comment]
I test it and still no sequences mapped to the taxid in the database.

> Database sequences                   100
Database letters                     3704518
Accessions in database               100
Entries in accession to taxid file   100
Database accessions mapped to taxid  0
Database sequences mapped to taxid   0
Database hash                        5d8f1bcd2273a28add77fa4344931973
Total time                           9.788000s

In the mean time, I also test the swiss prot database using the same code and diamond version, it works fine.

**Comment by GDKO** [comment]
Can you send me the files for the small test?

**Comment by huiifeng** [comment]
Yes, here is the top 100 sequences file
[

[top_100_sequences.fasta.txt](https://github.com/user-attachments/files/21006390/top_100_sequences.fasta.txt)

](url)

**Comment by GDKO** [comment]
It works as expected for the top100, so I have no idea why it fails on your end.
```
Database sequences                   100
Database letters                     3704518
Accessions in database               100
Entries in accession to taxid file   100
Database accessions mapped to taxid  100
Database sequences mapped to taxid   100
Database hash                        5d8f1bcd2273a28add77fa4344931973
Total time                           9.590000s
```

**Comment by GDKO** [comment]
Last thing can you send me a zip file containing all the files for the top100 test?

- Your original fasta
- Your fixed fasta
- The ```un.taxids```
- The ```db.dmnd```

**Comment by huiifeng** [comment]
Yes, please find it in attaced. I don't have a original fasta since it's too large.

THX a lot!

[100_seq.zip](https://github.com/user-attachments/files/21020489/100_seq.zip)

**Comment by GDKO** [comment]
It works fine on my end, so I don't know why it fails. Maybe if you redownload uniref will solve the problem.
