### ISSUE TITLE
how to infer donor species according to result file named fasttree_tree_results.txt_k5.prox.txt

### ISSUE THREAD

**Issue by njliangdong** [GDKO/AvP#12]
Hi, dear author, 
    I used AvP to perform genome-wide HGT events identification, and it work well. However, my next focus is how can I summarize the donor species of HGT candidates, from fastree output (phylogeny tree or anything else)?

Thanksa lot !

**Comment by GDKO** [comment]
Hi @njliangdong,

Have you run classify?

Cheers,
Georgios

**Comment by njliangdong** [comment]
> Hi @njliangdong,
> 
> Have you run classify?
> 
> Cheers, Georgios


> Hi @njliangdong,
> 
> Have you run classify?
> 
> Cheers, Georgios

yes, I do and one folder named Avp.classify was generated,  which include one file named 'classification_results.txt', I am not sure if this file provide the donor info of HGTs, thanks for your further reply !

**Comment by GDKO** [comment]
The classify command groups donors based on the classification file but with a broad taxonomic ranking (see [taxonomy file](https://github.com/GDKO/AvP/blob/master/depot/taxonomy.yaml)). Are you more interested in lower ranks?
