### ISSUE TITLE
Error parsing GFF3 file for AvP hgt local score analysis

### ISSUE THREAD

**Issue by aldendirks** [GDKO/AvP#13]
Your software has worked really well for me! I'm now trying to run the HGT local score script but am getting errors parsing the GFF3 file. 

```
Traceback (most recent call last):
  File "/nfs/turbo/lsa-tyjames/mycology/Alden/software/AvP/aux_scripts/hgt_local_score.py", line 169, in <module>
    main()
  File "/nfs/turbo/lsa-tyjames/mycology/Alden/software/AvP/aux_scripts/hgt_local_score.py", line 86, in main
    gene_scaf = gene_location[gene]
                ~~~~~~~~~~~~~^^^^^^
KeyError: 'Hydnotrya_cerebriformis_MICH67763_scaffold_3601_FUN_011721'
```

I wasn't sure if the GFF3 file should be the full annotations (gene, mRNA, exon, and CDS) or just the lines that are annotated as "gene" or just those annotated as "mRNA". I've tried all the different combos and it gives the same error. When I grep that ID it is found as a match in the file. My GFF3 has 9 columns in the same format specified so I'm not sure why it can't find the right line.

**Comment by aldendirks** [comment]
It ended up working with just the mRNA lines of the GFF3 file. There was a -T1 appended to the IDs from Funannotate so I had to remove those then it worked. Thanks!

**Comment by bheimbu** [comment]
Hi,

get the same error: 

```
$ ../../aux_scripts/hgt_local_score.py  -f NANCO@999999009@3_mRNA.gff -a 2000bp_og_core.out_ai.out_NANCO -t fasttree_general_results_NANCO.txt -m 0
Traceback (most recent call last):
  File "/scratch1/users/bheimbu/avp/oribatida/hgt_local_score/../../aux_scripts/hgt_local_score.py", line 169, in <module>
    main()
  File "/scratch1/users/bheimbu/avp/oribatida/hgt_local_score/../../aux_scripts/hgt_local_score.py", line 86, in main
    gene_scaf = gene_location[gene]
                ~~~~~~~~~~~~~^^^^^^
KeyError: 'scaffold7841_size5308'
``` 
I have no clue how to fix this, names in all files are the same like `scaffold7841_size5308`.

Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

Your scaffold names are also your gene names. So there is some issue there with how you generated your input.

Cheers,
Georgios

**Comment by bheimbu** [comment]
Hi @GDKO,

please can you check my attach files, if there are right. 

[2000bp_og_core.out_ai.out_NANCO.txt](https://github.com/GDKO/AvP/files/14944310/2000bp_og_core.out_ai.out_NANCO.txt)
[fasttree_general_results_NANCO.txt](https://github.com/GDKO/AvP/files/14944311/fasttree_general_results_NANCO.txt)
[NANCO@999999009@3_mRNA.gff.txt](https://github.com/GDKO/AvP/files/14944312/NANCO%40999999009%403_mRNA.gff.txt)

I didn't do the annotation, got the annotatiosn from someone else.


Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

Your gene names in ```2000bp_og_core.out_ai.out_NANCO.txt``` and ```fasttree_general_results_NANCO.txt``` are the same. However, your gene names in the gff file are not the same as the ones you used for running AvP. In the gff file they are named ```mRNA1, mRNA2 ... etc```.

**Comment by bheimbu** [comment]
Hi @GDKO 

that is, I should rerun the annotation or how to proceed?

To give you a bit more background info: I've used fDOG to search for orthologs of bacterial and fungal origin in oribatid genomes. The found orthologs were then used to search for HGTs with avp. That's why my names are so differently between gff and other files.

Cheers Bastian

**Comment by GDKO** [comment]
Hi @bheimbu,

The hgt_local_score was designed to check the locality of the genes detected as potential HGTs from AvP in the genome assembly. The idea is that if a gene is an HGT then it will be in a region surrounded by non-HGT genes. There can be a case of course that a bigger region was inserted into the genome. So this score can identify regions which are either contamination in the genome assembly or HGT-rich regions. 

I think you have misunderstood the purpose of this score. To run this program you need the genes and the gff of one assembly. For example, you have data from one oribatid genome. You run the AvP pipeline to identify potential HGT candidates from your gene set and then you run hgt_local_score to see in which regions in your genome those genes fall.

Cheers,
Georgios

**Comment by bheimbu** [comment]
Hi @GDKO 

I got the idea right, trust me. But I only want to know whether certain genes (found by fDOG) represent true HGTs or not. It's actually just a matter of how my data (i.e. gff files and output from fDOG) assigns names, right? So what I have to do is to manipulate my data to get it in the right format. 

My question would be: Do you have an example data set to see how the files should look like?


Cheers Bastian

**Comment by GDKO** [comment]
See here https://github.com/GDKO/AvP/wiki/tutorial

**Comment by GDKO** [comment]
Added a script to rename MetaEuk output files.
