### ISSUE TITLE
 I don't want to exclude any species.

### ISSUE THREAD

**Issue by maruiqi0710** [GDKO/AvP#15]
My target species is Saccharomyces cerevisiae, and I want to detect any horizontal gene transfer from other species, including other species in the Saccharomyces genus. I set groups.yaml to

```
Ingroup:
4932: S.cerevisiae
```

How should I fill in the EGP field? I don't want to exclude any species.

**Comment by GDKO** [comment]
Hi @maruiqi0710,

If you want to detect HGTs in S.cerevisiae I would recommend 
```
---
Ingroup:
 4930: Saccharomyces
EGP:
 4932: S.cerevisiae
```
This will identify HGTs that are present only in S.cerevisiae and not in other Saccharomyces species.

The problem by allowing HGTs from closely related species is that it we cannot distinguish between vertical and horizontal transfers.

**Comment by maruiqi0710** [comment]
I am a little confused now. Maybe my description wasn't accurate enough. My studied organism is _S.cerevisiae_, I want to know HGT from other species to _S.cerevisiae_, including from other _Saccharomyces_  species. If I set "Ingroup: 4930: Saccharomyces, EGP: 4932: S.cerevisiae", will I only detect HGTs from Non-_Saccharomyces_ species to _S.cerevisiae_?

**Comment by GDKO** [comment]
Let me explain with an example

Suppose your species of interest is S.cerevisiae with taxonomy 
```
phylum:Ascomycota;class:Saccharomycetes;order:Saccharomycetales;family:Saccharomycetaceae;genus:Saccharomyces
```
- If you set exclude to S.cerevisiae and ingroup to Saccharomyces you are searching for HGTs present in S.cerevisiae that are not present in Saccharomyces.
- If you set exclude to Saccharomyces and ingroup to Saccharomycetaceae you are searching for HGTs present in S.cerevisiae and maybe in other species from the genus Saccharomyces but absent in the other genera of Saccharomycetaceae

It is impossible to distinguish vertical from horizontal transmission in closely related species with AvP. If you set ingroup to S. cerevisiae then apart from novel genes in this specific species everything else will be HGT.

AvP is not suited for this type of analysis. If you want to find HGTs from other Saccharomyces species, I would recommend running a gene-tree vs species-tree type of analysis.
