### ISSUE TITLE
AttributeError: 'str' object has no attribute 'append'

### ISSUE THREAD

**Issue by wangzefei446** [GDKO/AvP#21]
hello,when I run the prepare.py,I got this problem,how can I solve it?
Traceback (most recent call last):
  File "/share/home/bgi_cwangzf/softare/AvP/depot/prepare.py", line 34, in <module>
    from depot.PetIO import check_programs, get_outdir, progress, open_file
  File "/share/home/bgi_cwangzf/miniconda3/lib/python3.10/site-packages/depot/__init__.py", line 25, in <module>
    from .storage import StorageWrapper
  File "/share/home/bgi_cwangzf/miniconda3/lib/python3.10/site-packages/depot/storage.py", line 13, in <module>
    libcloud.security.CA_CERTS_PATH.append(os.path.join(_base_path, 'cacert.pem'))
AttributeError: 'str' object has no attribute 'append'

**Comment by GDKO** [comment]
Hi @wangzefei446, 

Can you share your prepare command and your config file?

Cheers,
Georgios

**Comment by wangzefei446** [comment]
> Please take a look at the wiki on how to properly run the software
> 
> > /share/home/bgi_cwangzf/softare/AvP/depot/prepare.py -a 126.out_ai.out -o /share/home/bgi_cwangzf/database/NR/126 -f 126.faa -b 126.out -x groups.yaml -c config.yaml
> 
> Your command should be like this
> 
> `/share/home/bgi_cwangzf/softare/AvP/avp prepare -a 126.out_ai.out -o /share/home/bgi_cwangzf/database/NR/126 -f 126.faa -b 126.out -x groups.yaml -c config.yaml `
> 
> Also another issue, I have noticed that you provide a fasta_path together with your blast_db_path, and I am guessing that NR_220531 is a directory.
> 
> Before continuing what was your blast command?

Excuse me, I'll ask you a question，the  blast_db_path is nr_blast_db_path,the fasta_path，what does it refer to？

**Comment by GDKO** [comment]
- If you use NR the recommendation is to use blast against it and set the blast_db_path to your NR database path (the same as your blast command [-db option]).
- If you use other databases the recommendation is to use diamond with some specific formatting. Then you set the fasta_path to your database fasta file.

You can read more [here](https://github.com/GDKO/AvP/wiki/Setting-up#Databases).
