### ISSUE TITLE
avp prepare issue

### ISSUE THREAD

**Issue by dddai13** [GDKO/AvP#26]
Hi, When I run avp prepare, I always get an error "'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte". The details are as below:
Traceback (most recent call last):
  File "/group/siddiquegrp/tools/AvP/avp", line 7, in <module>
    main()
  File "/group/siddiquegrp/tools/AvP/depot/interface.py", line 29, in main
    prepare.main()
  File "/group/siddiquegrp/tools/AvP/depot/prepare.py", line 257, in main
    for record in SeqIO.parse(handle,"fasta"):
  File "/group/siddiquegrp/miniconda3/envs/avp/lib/python3.12/site-packages/Bio/SeqIO/Interfaces.py", line 91, in __next__
    return next(self.records)
           ^^^^^^^^^^^^^^^^^^
  File "/group/siddiquegrp/miniconda3/envs/avp/lib/python3.12/site-packages/Bio/SeqIO/FastaIO.py", line 196, in iterate
    for title, sequence in SimpleFastaParser(handle):
  File "/group/siddiquegrp/miniconda3/envs/avp/lib/python3.12/site-packages/Bio/SeqIO/FastaIO.py", line 49, in SimpleFastaParser
    for line in handle:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte

Could you please help me to solve this problem? thanks.

**Comment by GDKO** [comment]
Hi @dddai13,

Can you post your `avp prepare` command and also attach your config file?

Cheers,
Georgios

**Comment by dddai13** [comment]
Hi, my command is "~/software/AvP/avp prepare -a A1.similarity.out_ai.out -o A1_avp -f A1.prot.fasta -b A1.similarity.out -x groups.yaml -c config.yaml"
I used the example config file, as below:
---
max_threads: 4

# DB path
blast_db_path: nr    # blast: change to the local blast_db path
fasta_path: /group/siddiquegrp/tools/AvP/unire90/uniref90.fasta.dmnd  # diamond: change to the local fasta path for sp, ur90, or custom database
mode: ur90    # use blast for blast database, use sp for swissprot database, ur90 for uniref90 or custom database
data_type: AA    # data type DNA, AA

## Algorithm options
# prepare
ai_cutoff: 10
ahs_cutoff: 0
outg_pct_cutoff: 80
selection: "(ai or ahs) and outg_pct" # select sequences based on which metrics, another example "(ai or ahs) and outg_pct"
percent_identity: 100   # select hits equal or below this number
cutoffextend: 20    # when ingroup hit is found, we take this hit + n hits
number_hits_noingroup: 50   # when no ingroup hit is found, we take this number of hits
trimal: false
min_num_hits: 4   # select queries with at least that many blast hits
percentage_similar_hits: 0.7  # group queries based on this
# detect, clasify, evaluate
fastml: true  # Use fasttree instead of IQTree
node_support: 0  # nodes below that number will collapse
complex_per_ingroup: 20   # if D/(D+I) smaller than this then node is considered Ingroup
complex_per_donor: 80   # if D/(D+I) greater than this then node is considered Donor
complex_per_node: 90  # if node contains percent number of this category, it is assigned

# Program specific options
mafft_options: '--anysymbol --auto'
trimal_options: '-automated1'

#IQ-Tree
iqmodel: '-mset WAG,LG,JTT -AICc -mrate E,I,G,R'
ufbootstrap: 1000
iq_threads: 4

Thank you so much!

**Comment by GDKO** [comment]
Hi @dddai13, 

See [here](https://github.com/GDKO/AvP/wiki/Setting-up#uniref90) on how to format uniref90 if you haven't done already, and use the fasta file (the one you used in `diamond makedb` with `--in)` instead of the dmnd file in the config.

Cheers,
Georgios

**Comment by dddai13** [comment]
OMG, thank you so much! It is the dmnd file's issue.
