### ISSUE TITLE
Database download error [Swissprot]

### ISSUE THREAD

**Issue by byeollee** [GDKO/AvP#9]
Hello, I am writing because I am having issues downloading a database. 

While downloading Swissprot, I encountered an error while performing the makedb task in Diamond: 'Error: Invalid option: taxonnames'. 

Could you please advise me on how to resolve this issue?

Thank you.

**Comment by GDKO** [comment]
Hi @byeollee,

Can you check the version number of diamond? Sometimes conda installs a very old version v0.9.xx. If that is the case you have to remove the old version and install the newest version from [here](https://github.com/bbuchfink/diamond).

Let me know if that solves the problem.

**Comment by GDKO** [comment]
I have updated the wiki to suggest downloading diamond from the github page.
